#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    args.context = "personal_ci"
    args.mode = "manual"
    args.cluster = false

    # ------------
    # Tests to run
    # ------------

    test_upgrade_from.fea498cd83a7da12a102efe2f47397dace3cddda.name = "2021-09-22~ynh1"
